# Generated by Django 4.2 on 2023-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
