# Generated by Django 4.2 on 2023-04-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_produto_categoria_alter_produto_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('CASA', 'Casa'), ('ELETRONICOS', 'Eletrônicos'), ('LIVROS', 'Livros'), ('DECORACAO', 'Decoração')], default='', max_length=50),
        ),
    ]
