# Generated by Django 4.2 on 2023-04-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_produto_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='', max_length=50),
        ),
    ]
